# Q3 Using Scikit-Learn

In [31]:
import numpy as np
import pandas as pd
import time
import gc

from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
# Import statements run before running other code cells

# Classifier Setup

In [32]:
# XXX
# TODO: Read in all the data. Replace the 'xxx' with the path to the data set.
# XXX

# data = pd.read_csv('xxx')

# Separate out the x_data and y_data.
# x_data = data.loc[:, data.columns != "y"]
# y_data = data.loc[:, "y"]

# -------------------------------
# ADD CODE HERE
data = pd.read_csv('pulsar_stars.csv')
x_data = data.loc[:, data.columns != "y"]
y_data = data.loc[:, "y"]
# ------------------------------

In [33]:
# The random state to use while splitting the data.
# random_state = 100

# XXX
# TODO: Split 70% of the data into training and 30% into test sets. Call them x_train, x_test, y_train and y_test.
# Use the train_test_split method in sklearn with the parameter 'shuffle' set to true and the 'random_state' set to 100.
# XXX

# -------------------------------
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.3, random_state = 100, shuffle = True)
# ------------------------------

# Linear Regression 

In [34]:
# XXX
# TODO: Create a LinearRegression classifier and train it.
# XXX

# -------------------------------
linreg = LinearRegression()
linreg.fit(x_train, y_train)
# -------------------------------

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
y_predicted = np.around(linreg.predict(x_train))
print(accuracy_score(y_train, y_predicted))
# -------------------------------

0.9703065134099617


In [36]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# ------------------------------
y_predicted_test = np.around(linreg.predict(x_test))
print(accuracy_score(y_test, y_predicted_test))
# -------------------------------

0.9715083798882681


# Random Forest Classifier

In [37]:
# XXX
# TODO: Create a RandomForestClassifier and train it.
# WARNING: Ignore "FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22."10 in version 0.20 to 100 in 0.22."
# XXX

# -------------------------------
forest = RandomForestClassifier(max_depth = 2, random_state = 0)
forest.fit(x_train, y_train)
# -------------------------------

c:\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [38]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
y_train_predicted = forest.predict(x_train)
y_train_predicted = np.around(y_train_predicted)
print(accuracy_score(ytrain, y_train_predicted))
# -------------------------------

0.971823116219668


In [39]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE

y_test_predicted = forest.predict(x_test)

y_test_predicted = np.around(y_test_predicted)
print(accuracy_score(y_test, y_test_predicted))
# -------------------------------

0.9746741154562384


## Feature Importance

In [40]:
# XXX
# TODO: Determine and print the feature importance as evaluated by the Random Forest Classifier.
# XXX

# -------------------------------
# ADD CODE HERE

imp = forest.feature_importances_
print(imp)
# -------------------------------

[0.34729384 0.03715007 0.22167527 0.33015243 0.01288577 0.04705813
 0.         0.00378449]


In [41]:
# XXX
# TODO: Sort them in the descending order and print the feature numbers[0 to ...].
#       Hint: There is a direct function available in sklearn to achieve this. Also checkout argsort() function in Python.
# XXX

# -------------------------------
# ADD CODE HERE

sort_features = np.argsort(imp)
print(sort_features)
# -------------------------------

[6 7 4 1 5 2 3 0]


## Hyper-parameter Tuning

In [42]:
# XXX
# TODO: Tune the hyper-parameters 'n_estimators' and 'max_depth'.
# XXX

# -------------------------------
# ADD CODE HERE

forest = RandomForestClassifier()
n_estimators = [int(x) for x in np.linspace(10, 500, num = 10)]
max_depth = [int(x) for x in np.linspace(2, 20, num = 8)]

params = {}

params['n_estimators'] = n_estimators

params['max_depth'] = max_depth

grid_search_train = GridSearchCV(estimator = forest, param_grid = params, cv = 10, n_jobs = -1, verbose = 2)

grid_search_test = GridSearchCV(estimator = forest, param_grid = params, cv = 10, n_jobs = -1, verbose = 2)
# -------------------------------

In [43]:
# XXX
# TODO: Print the best params, using .best_params_
# XXX

# -------------------------------
# ADD CODE HERE

grid_search_train.fit(x_train, y_train)
grid_search_test.fit(x_test, y_test)

print(grid_search_train.best_params_)
print(grid_search_test.best_params_)
# -------------------------------

Fitting 10 folds for each of 80 candidates, totalling 800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    6.4s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  8.3min
[Parallel(n_jobs=-1)]: Done 800 out of 800 | elapsed: 11.8min finished


Fitting 10 folds for each of 80 candidates, totalling 800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    5.0s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   39.4s
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  4.3min


{'max_depth': 17, 'n_estimators': 10}
{'max_depth': 12, 'n_estimators': 10}


[Parallel(n_jobs=-1)]: Done 800 out of 800 | elapsed:  5.8min finished


In [44]:
# XXX
# TODO: Print the best score, using .best_score_.
# XXX

# -------------------------------
# ADD CODE HERE

print(grid_search_train.best_score_)
print(grid_search_test.best_score_)
# -------------------------------

0.979007024265645
0.9837988826815642


# Support Vector Machine

## Pre-process

In [45]:
# XXX
# TODO: Pre-process the data to standardize or normalize it, otherwise the grid search will take much longer.
# Warning: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning"
# XXX

# -------------------------------
norm_train = normalize(x_train, norm = 'l2')
norm_test = normalize(x_test, norm = 'l2')
# -------------------------------

In [46]:
# XXX
# TODO: Create a SVC classifier and train it.
# XXX

# -------------------------------
SVM = SVC(gamma = 'auto')
SVM.fit(norm_train, y_train)
# -------------------------------

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [47]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX
# WARNING: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.""

# -------------------------------
y_predicted_svm = SVM.predict(norm_train)
print(accuracy_score(y_predicted_svm, y_train))
# -------------------------------

0.966794380587484


In [48]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX
# WARNING: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.""

# -------------------------------
y_predicted_svm_test = SVM.predict(norm_test)
print(accuracy_score(y_predicted_svm_test, y_test))
# -------------------------------

0.970391061452514


## Hyper-parameter Tuning

In [49]:
# XXX
# TODO: Tune the hyper-parameters 'C' and 'kernel' (use rbf and linear).
# XXX

# -------------------------------
SVM_tune_params = {'kernel':('linear', 'rbf'), 'C':[0.0001, 0.1, 100]}
SVM_2 = GridSearchCV(SVC(gamma = 'scale'), SVM_tune_params, cv=10)
SVM_2.fit(norm_train, y_train)
# -------------------------------

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.0001, 0.1, 100], 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [50]:
# XXX
# TODO: Print the best score, using .best_score_.
# XXX

# -------------------------------
print(SVM_2.best_score_)
# -------------------------------

0.9755747126436781


In [51]:
# XXX
# TODO: Get the training and test set accuracy values after hyperparameter tuning.
# XXX

# -------------------------------
y_SVM_2_predicted = SVM_2.predict(norm_train)
print(accuracy_score(y_SVM_2_predicted, ytrain))
y_SVM_2_predicted_test = SVM_2.predict(norm_test)
print(accuracy_score(y_SVM_2_predicted_test, ytest))
# -------------------------------

0.9764527458492975
0.9772811918063314


In [52]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
y_SVM_2_predicted_train = SVM_2.predict(norm_train)
y_SVM_2_predicted_train = np.around(y_SVM_2_predicted_train)
print(accuracy_score(y_SVM_2_predicted_train, ytrain))
# -------------------------------

0.9764527458492975


In [53]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
y_SVM_2_predicted_test = SVM_2.predict(norm_test)
y_SVM_2_predicted_test = np.around(y_SVM_2_predicted_test)
print(accuracy_score(y_SVM_2_predicted_test, ytest))
# -------------------------------

0.9772811918063314


In [54]:
# XXX
# TODO: Calculate the rank test score, mean testing score and mean fit time for the 
# best combination of hyperparameter values that you obtained in Q3.2. The GridSearchCV 
# class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
print(SVM_2.cv_results_['rank_test_score'])
print(SVM_2.cv_results_['mean_test_score'])
print(SVM_2.cv_results_['mean_fit_time'])
# -------------------------------

[5 5 4 3 2 1]
[0.90876437 0.90876437 0.96328225 0.96703384 0.97405811 0.97557471]
[0.5560071  0.55412655 0.16473231 0.2818903  0.18555315 0.39558313]


In [55]:
# XXX
# TODO: Print the rank test score for the best combination of hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
print(SVM_2.cv_results_['rank_test_score'])
# -------------------------------

[5 5 4 3 2 1]


In [56]:
# XXX
# TODO: Print mean testing score for the best combination of hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
print(SVM_2.cv_results_['mean_test_score'])
# -------------------------------

[0.90876437 0.90876437 0.96328225 0.96703384 0.97405811 0.97557471]


In [57]:
# XXX
# TODO: Print mean fit time for the best combination of hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
print(SVM_2.cv_results_['mean_fit_time'])
# -------------------------------

[0.5560071  0.55412655 0.16473231 0.2818903  0.18555315 0.39558313]


# PCA

In [58]:
# XXX
# TODO: Perform dimensionality reduction of the data using PCA.
#       Set parameters n_component to 8 and svd_solver to 'full'. Keep other parameters at their default value.
# XXX

# -------------------------------
Decomposition = PCA(n_components = 8, svd_solver = 'full')
Decomposition.fit(x_train)
# -------------------------------

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
    svd_solver='full', tol=0.0, whiten=False)

In [59]:
# XXX
# TODO: Print Percentage of variance explained by each of the selected components
# XXX

# -------------------------------
print(Decomposition.explained_variance_ratio_)
# -------------------------------

[8.71054855e-01 7.80404050e-02 4.12747422e-02 6.15520409e-03
 2.45425694e-03 9.78533643e-04 3.91429289e-05 2.85984066e-06]


In [60]:
# XXX
# TODO: The singular values corresponding to each of the selected components.
# XXX

# -------------------------------
print(Decomposition.singular_values_)
# -------------------------------

[11992.97512747  3589.74779466  2610.63625426  1008.15059028
   636.59642313   401.9685368     80.39533321    21.73076915]
